version: 2

project_name: stream-share

builds:
  - binary: stream-share
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -a
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

archives:
  -
   format_overrides:
     - goos: windows
       format: zip

release:
  github:
    owner: lucasduport
    name: stream-share
  draft: false

nfpms:
  -
   vendor: Lucas Duport
   homepage: https://github.com/lucasduport/stream-share
   maintainer: Lucas Duport <lucas.duport@epita.fr>
   description: IPTV Proxy with LDAP support
   license: Apache 2.0
   formats:
     - deb
     - rpm

dockers:
  - image_templates:
    - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-arm64"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}-arm64"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}-arm64"
    - "ghcr.io/lucasduport/stream-share:latest-arm64"
    - "lucasduport/stream-share:{{ .Tag }}-arm64"
    - "lucasduport/stream-share:v{{ .Major }}-arm64"
    - "lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}-arm64"
    - "lucasduport/stream-share:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

  - image_templates:
    - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-amd64"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}-amd64"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/lucasduport/stream-share:latest-amd64"
    - "ghcr.io/lucasduport/stream-share:{{ .Tag }}"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}"
    - "ghcr.io/lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/lucasduport/stream-share:latest"
    - "lucasduport/stream-share:{{ .Tag }}-amd64"
    - "lucasduport/stream-share:v{{ .Major }}-amd64"
    - "lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}-amd64"
    - "lucasduport/stream-share:latest-amd64"
    - "lucasduport/stream-share:{{ .Tag }}"
    - "lucasduport/stream-share:v{{ .Major }}"
    - "lucasduport/stream-share:v{{ .Major }}.{{ .Minor }}"
    - "lucasduport/stream-share:latest"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser