version: 2

project_name: iptv-proxy

builds:
  - binary: iptv-proxy
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
      - -a
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

archives:
  -
   format_overrides:
     - goos: windows
       format: zip

release:
  github:
    owner: lucasduport
    name: iptv-proxy
  draft: false

nfpms:
  -
   vendor: Lucas Duport
   homepage: https://github.com/lucasduport/iptv-proxy
   maintainer: Lucas Duport <lucas.duport@epita.fr>
   description: IPTV Proxy with LDAP support
   license: Apache 2.0
   formats:
     - deb
     - rpm

dockers:
  - image_templates:
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:{{ .Tag }}-arm64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}-arm64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}.{{ .Minor }}-arm64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - iptv-proxy
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

  - image_templates:
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:{{ .Tag }}-amd64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}-amd64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}.{{ .Minor }}-amd64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:latest-amd64"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:{{ .Tag }}"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:v{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/lucasduport/iptv-proxy/iptv-proxy:latest"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
    - iptv-proxy
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser