version: "3"

services:
  iptv-proxy:
    image: lucasduport/iptv-proxy:latest
    container_name: iptv-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # M3U Configuration
      M3U_URL: ""                      # URL or path to M3U file
      M3U_FILE_NAME: "iptv.m3u"        # Name of the generated M3U file
      M3U_CACHE_EXPIRATION: "24"       # Cache expiration in hours

      # Server Configuration
      PORT: 8080                       # Port to listen on
      ADVERTISED_PORT: 443             # Port to advertise in URLs (for reverse proxy)
      HOSTNAME: ""                     # Hostname to use in URLs
      GIN_MODE: "release"              # Gin mode (debug or release)
      HTTPS: "1"                       # Use HTTPS in generated URLs
      CUSTOM_ENDPOINT: ""              # Custom endpoint path
      CUSTOM_ID: ""                    # Custom ID for URL paths
      
      # Xtream Configuration
      XTREAM_USER: ""                  # Xtream API username
      XTREAM_PASSWORD: ""              # Xtream API password
      XTREAM_BASE_URL: ""              # Xtream API base URL
      XTREAM_API_GET: "false"          # Generate get.php from API
      
      # Legacy authentication (when LDAP is disabled)
      USER: ""                         # Username for basic auth
      PASSWORD: ""                     # Password for basic auth
      
      # Debug options
      DEBUG_LOGGING: "true"            # Enable debug logging
      CACHE_FOLDER: "/root/.iptv-proxy/cache"   # Folder to save responses
      
      # LDAP Authentication
      LDAP_ENABLED: "true"             # Enable LDAP authentication
      LDAP_SERVER: ""                  # LDAP server URL (ldap://server:389)
      LDAP_BASE_DN: "ou=people,dc=example,dc=com"  # Base DN for user search
      LDAP_BIND_DN: "uid=admin,ou=people,dc=example,dc=com"  # Bind DN for service account
      LDAP_BIND_PASSWORD: ""           # Bind password for service account
      LDAP_USER_ATTRIBUTE: "uid"       # LDAP attribute containing username
      LDAP_GROUP_ATTRIBUTE: "memberOf" # LDAP attribute for group membership
      LDAP_REQUIRED_GROUP: "iptv"      # Group required for authentication

    volumes:
      - iptv_config:/root/.iptv-proxy  # Persistent configuration storage

volumes:
  iptv_config:
